### ISSUE TITLE
[FEATURE]: need help to translate to French,

### ISSUE THREAD

**Issue by punkyard** [drl990114/MarkFlowy#500]
**Is your feature request related to a problem? Please describe.**
only two languages available?

**Describe the solution you'd like**
a file of english terms for pull request of french version

**Describe alternatives you've considered**
simple file to transmit translation 

great app!

**Comment by drl990114** [comment]
Because I am currently maintaining the project alone and have limited energy, so in the plan I will only maintain Chinese and English.

The internationalization module still needs to be refactored so that everyone can better participate in contribution and use. I will post it here when this part is completed.

**Comment by punkyard** [comment]
Then I will keep an eye on it ;)
But any time you're ready.. I'll do the job!

teacher in public high school

**Comment by drl990114** [comment]
Thank you, I will increase the priority of this work.

**Comment by yu2chuan** [comment]
more and more people like this work.

**Comment by drl990114** [comment]
@punkyard Hi, the basic reconstruction of the multi-language part has been completed. Everyone is welcome to participate and contribute more language versions.

Related documents can be read at [contributing.md](https://github.com/drl990114/MarkFlowy/blob/main/docs/docs/Community/CONTRIBUTING.md).
