### ISSUE TITLE
Would like to add the ability to associate files!!!

### ISSUE THREAD

**Issue by sr79368142** [drl990114/MarkFlowy#737]
Would like to add the ability to associate files!!!

Great markdown editor, everything is perfect, small, powerful and quick to start. I wonder if the future plans are as a pure editor or a note taking software?
When I enter the window I have to add a folder before I can edit the .md file, so it's just for future notes management, isn't it?
If it's a pure editor, I'd like to add the ability to associate .md files, so that double-clicking on a .md file will open it up for editing directly in the app.
The various mainstream md editors on windows are too big and have delays in startup speed for previewing. Many markdown users on windows need this feature!
There is also the md package file format, textbundle and textpack these two, also hope that the can consider the support, although it is not necessary, but there will be used in the scene, at present almost no windows editor support these two functions!
I hope can consider to consider! Thank you very much!
------------------------------------------------------------------------
很棒的markdown编辑器，一切都完美，体积小巧，功能强大，启动迅速。不知道大佬未来的打算是作为纯粹的编辑器还是一款笔记软件？
我进入窗口后要求先添加文件夹才能编辑.md文件，这样的话就是为未来的笔记管理预设的吧？
如果是作为纯粹的编辑器，我希望能增加关联.md文件的功能，这样直接双击.md文件就能直接在应用里打开查看编辑了。
windows上的各种主流md编辑器体积都太大了，启动速度有延迟，不适合预览的。很多windows上的markdown用户都需要这个功能！
还有就是md的包文件格式，textbundle和textpack这两种，也希望大佬能够考虑一下支持的，虽然不是必须的，但也有会用到的场景，目前几乎没有windows的编辑器支持这两个功能的！！！
希望大佬能考虑考虑的！！非常感谢！！！

**Comment by drl990114** [comment]
Thank you for your recognition. Based on my current plan, I hope to create a markdown editor with a certain note taking function, so that users can easily record lightweight things. In the future, I will do some integration and support cloud storage such as GitHub and Google Drive. Of course, we also consider developing our own cloud services, but it all depends on the feedback from the market and users.

Regarding the support for file shortcut opening, some users have previously provided feedback on it, and I will increase its priority.

In addition, I didn't have a lot of knowledge about textbundle and textpack before. After a brief understanding, it seems to be a convenient markdown storage format mainly used for data synchronization and storage, similar to Pandoc? (If I am not accurate, please correct me at any time). I will consider it, but I need more time to consider and implement the specific priorities because there are too many things to do at the moment.

**Comment by sr79368142** [comment]
You're a great developer, thanks for the prompt reply!
pandoc is a conversion app that converts md files to other formats, and textbundle is a file format that pandoc can convert md to both of those formats when set up properly.
I will continue to experience MarkFlowy and hope it gets better and better! It's an excellent software to love!!!!
I'll keep you posted if there are better features that need to be implemented. I wish you all the best in your endeavors!

Translated with DeepL.com (free version)

**Comment by drl990114** [comment]
Thank you, I will do my best to implement these features as soon as possible.
